"use client";
import { useMemo, useState } from "react";
import { Minus, Plus, ShoppingCart } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";

type Product = { id: string; name: string; description: string | null; price: string; currency: "USD" | "LBP"; imageUrl: string | null; stock: string | null; type: "PRODUCT" | "SERVICE" };
export function PublicCatalog({ slug, products, orderingEnabled }: { slug: string; products: Product[]; orderingEnabled: boolean }) {
  const [cart, setCart] = useState<Record<string, number>>({}); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [address, setAddress] = useState(""); const [notes, setNotes] = useState(""); const [fulfillment, setFulfillment] = useState("PICKUP"); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const items = products.filter((p) => (cart[p.id] ?? 0) > 0); const currencies = [...new Set(items.map((p) => p.currency))]; const mixed = currencies.length > 1;
  const total = useMemo(() => items.reduce((sum, p) => sum + Number(p.price) * (cart[p.id] ?? 0), 0), [items, cart]);
  function change(id: string, delta: number) { setCart((current) => ({ ...current, [id]: Math.max(0, (current[id] ?? 0) + delta) })); }
  async function submit() { if (!items.length || !name.trim() || !phone.trim() || mixed) return; setLoading(true); setMessage(null); try { const r = await fetch(`/api/public/${slug}/orders`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ customerName: name, customerPhone: phone, fulfillment, address: address || undefined, notes: notes || undefined, items: items.map((p) => ({ productId: p.id, quantity: String(cart[p.id]) })) }) }); const j = await r.json(); if (!r.ok) throw new Error(j.message ?? j.error ?? "Unable to place order"); setMessage(`Order received: ${j.orderNumber}`); setCart({}); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to place order"); } finally { setLoading(false); } }
  return <div className="space-y-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{products.map((p) => <article key={p.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">{p.imageUrl ? <img src={p.imageUrl} alt="" className="h-44 w-full object-cover" /> : <div className="h-28 bg-slate-100" />}<div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{p.name}</h3>{p.description ? <p className="mt-1 line-clamp-2 text-xs text-slate-500">{p.description}</p> : null}</div><strong className="whitespace-nowrap">{p.price} {p.currency}</strong></div>{orderingEnabled ? <div className="mt-4 flex items-center justify-end gap-2"><Button size="icon" variant="outline" onClick={() => change(p.id, -1)}><Minus className="size-4" /></Button><span className="w-7 text-center text-sm font-bold">{cart[p.id] ?? 0}</span><Button size="icon" onClick={() => change(p.id, 1)}><Plus className="size-4" /></Button></div> : null}</div></article>)}</div>
    {orderingEnabled ? <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShoppingCart className="size-5" /><h2 className="text-xl font-black">Your order</h2></div><div className="mt-4 space-y-2">{items.length ? items.map((p) => <div key={p.id} className="flex justify-between text-sm"><span>{cart[p.id]} × {p.name}</span><span>{(Number(p.price) * cart[p.id]).toFixed(p.currency === "USD" ? 2 : 0)} {p.currency}</span></div>) : <p className="text-sm text-slate-500">Your cart is empty.</p>}</div>{items.length ? <><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Name" /><Input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Phone" /><Select value={fulfillment} onChange={(e) => setFulfillment(e.target.value)}><option value="PICKUP">Pickup</option><option value="DELIVERY">Delivery</option><option value="DINE_IN">Dine in</option></Select><Input value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Address (for delivery)" /><Input className="sm:col-span-2" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Order notes (optional)" /></div><div className="mt-4 flex items-center justify-between"><div><p className="text-xs text-slate-500">Total</p><p className="text-xl font-black">{mixed ? "—" : `${total.toFixed(currencies[0] === "USD" ? 2 : 0)} ${currencies[0] ?? ""}`}</p></div><Button onClick={submit} disabled={loading || mixed || !name.trim() || !phone.trim()}>{loading ? "Sending..." : "Place order"}</Button></div>{mixed ? <p className="mt-3 text-xs text-red-600">This cart contains mixed currencies. Order items in one currency at a time.</p> : null}</> : null}{message ? <p className="mt-3 text-sm font-medium text-slate-700">{message}</p> : null}</section> : null}
  </div>;
}
